### ISSUE TITLE
name the cadence

### ISSUE THREAD

**Issue by MelissaGraham** [fedhere/Explosive-Physics-Fast-Transients-White-Paper-Cadence#15]
It seems it might be handy to have a proper name by which to call this cadence (though "Fast Transients Cadence" would work ok too). I propose something like "Presto-Colore" (because that's quick-colors in Italian if my Google translate is functioning) and that we use {\em } for it.

But if we decide we hates it, a quick search-and-replace can remove all mentions...

**Comment by fedhere** [comment]
Meliss and I converged, we are going with PrestoColor
