### ISSUE TITLE
should we have a section 6?

### ISSUE THREAD

**Issue by MelissaGraham** [fedhere/Explosive-Physics-Fast-Transients-White-Paper-Cadence#17]
The DESC WFD white paper has a Section 6, "Requests for New OpSim Runs" where they state the types of features they would like to see simulated. Should we have one also?

**Comment by fedhere** [comment]
I think our request is pretty clear, but we can add a table?

**Comment by MelissaGraham** [comment]
Hmmm, well if Section 6 isn't a part of the updated template, then I suppose the DESC WFD paper has made themselves a Section 6 to list all their requests because they are making such a variety of requests. Perhaps we just don't need one, and, if it's not a mandatory section, then no worries!
