### ISSUE TITLE
table

### ISSUE THREAD

**Issue by fedhere** [fedhere/Explosive-Physics-Fast-Transients-White-Paper-Cadence#7]
We need to fill in this table asap:

|        Properties | Importance |
| ------------- |:-------------:| 
|        Image quality |     |
|        Sky brightness |     |
|       Individual image depth |      |
|        Co-added image depth |  3    |
|        Number of exposures in a visit   |      |
|        Number of visits (in a night)  |   1   |
|        Total number of visits |   3   |
|        Time between visits (in a night) |     1 |
|        Time between visits (between nights)  |      |
|        Long-term gaps between visits |      |
|        Other (please add other constraints as needed) | 1 (filters)    |

Constraint Rankings: Summary of the relative importance of various survey strategy constraints. Please rank the importance of each of these considerations, from 1=very important, 2=somewhat important, 3=not important. If a given constraint depends on other parameters in the table, but these other parameters are not important in themselves, please only mark the final constraint as important. For example, individual image depth depends on image quality, sky brightness, and number of exposures in a visit; if your science depends on the individual image depth but not directly on the other parameters, individual image depth would be `1' and the other parameters could be marked as `3', giving us the most flexibility when determining the composition of a visit, for example.

**Comment by rbiswas4** [comment]
I would suggest

|        Properties | Importance |
| ------------- |:-------------:| 
|        Image quality |     3 |
|        Sky brightness |    3 |
|       Individual image depth |  3    |
|        Co-added image depth |  3    |
|        Number of exposures in a visit   |  3    |
|        Number of visits (in a night)  |     1 |
|        Total number of visits |    3  |
|        Time between visits (in a night) |     1 |
|        Time between visits (between nights)  |  2    |
|        Long-term gaps between visits |    3  |
|        Other (please add other constraints as needed) | 2 (filters)    |


Number of visits in a night is important only if we need >= 3 points. I think individual image depth is somewhat important, but we won't care if it goes down by a mag or more if these things can be achieved. Time between visits (between night) is useful, to know where things are rising from.

**Comment by igorandreoni** [comment]
> I would suggest
> 
> Properties	Importance
> Image quality	3
> Sky brightness	3
> Individual image depth	3
> Co-added image depth	3
> Number of exposures in a visit	3
> Number of visits (in a night)	1
> Total number of visits	3
> Time between visits (in a night)	1
> Time between visits (between nights)	2
> Long-term gaps between visits	3
> Other (please add other constraints as needed)	2 (filters)
> Number of visits in a night is important only in that we need >= 3 points, but we don't care if there are more. I think individual image depth is somewhat important, but we won't care if it goes down by a mag or more if these things can be achieved. Time between visits (between night) is useful, to know where things are rising from.

**Comment by igorandreoni** [comment]
Apologies, I closed the issue by mistake while trying to remove my blank comment.  All I wanted to say is that I fully agree with Rahul's proposal.

**Comment by fedhere** [comment]
I will set the filters back to 1; if we turn out to have a significant flexibility in a data-driven way when we have proper metrics we can send it back to 2 but it is not clear to me at all that any filter pairing would lead to useful color information for us

**Comment by rbiswas4** [comment]
@fedhere 👍  Totally  agree. 

Sorry that was a mistake on my part: When I wrote that I was writing 2 to mean we need at least 2 filters, and not the importance (since we were bothering to put in our own constraint it is obviously important). So, I think everyone is in agreement with raising the importance to 1. We can be more specific on what pairs of filters we want.
